object BuildDependenciesVersions {
    const val GRADLE_ANDROID = "8.1.2"
    const val KOTLIN = "1.8.22"
    const val NAVIGATION = "2.7.5"
    const val APPCOMPAT = "1.6.1"
    const val MATERIAL = "1.9.0"
    const val LIFECYCLE = "2.5.1"
    const val LIFECYCLE_COMPOSE = "2.6.2"
    const val CORE_KTX = "1.12.0"
    const val ROOM = "2.6.0"
    const val HILT = "2.48"
    const val HILT_ANDROID_X = "1.1.0"
    const val TIMBER = "5.0.1"
    const val RETROFIT = "2.9.0"
    const val LOGGING = "4.9.2"
    const val MOSHI = "1.12.0"
    const val COROUTINES = "1.6.4"
    const val KOTLIN_COMPILER_EMBEDDABLE = "1.9.0"
    const val COIL = "1.4.0"
    const val COMPOSE = "1.5.4"
    const val COMPOSE_BOM = "2023.10.01"
    const val COMPOSE_COMPILER = "1.5.2"
    const val COMPOSE_UI = "1.5.4"
    const val MATERIAL3 = "1.0.0"
    const val CONSTRAIN_LAYOUT = "1.0.0"
    const val ACTIVITY_COMPOSE = "1.3.1"
    const val PAGING = "3.2.1"
    const val ACCOMPANIST = "0.23.0"
    const val SKYDOVES = "1.2.3"
    const val CHUCKER = "3.5.2"

    // Tests
    const val TEST = "1.3.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.1"
    const val MOCKITO = "2.23.0"
}